version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "boto3"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "ruff"
        update-types: [ "version-update:semver-patch" ]